services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passord123
      MYSQL_DATABASE: tverr    
      
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/dump:/docker-entrypoint-initdb.d/

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u bedrift --password=Passord123
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
      
  app:
    build: .
    #command: gunicorn --bind 0.0.0.0:8000 eCommerce.wsgi:application
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 eCommerce.wsgi:application"
    volumes:
      - .:/usr/src/app
      - static_volume:/static
    ports:
      - "8000"
    depends_on:
        db:
         condition: service_healthy
    deploy:
      replicas: 2
      
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
    depends_on:
      - app

volumes:
  static_volume:
      
#    image: sqlserv
#    environment:
#      MYSQL_ROOT_PASSWORD: Passord123
#      MYSQL_DATABASE: tverr